import json
from flask import Flask, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)  # This will enable CORS for all origins

# Provided data
students_marks = [
    {"name": "GntJrxC86", "marks": 20},
    {"name": "iWu", "marks": 91},
    {"name": "0WVc2sNnm", "marks": 64},
    {"name": "6", "marks": 86},
    {"name": "f402y0Yk", "marks": 36},
    {"name": "fz6xy", "marks": 73},
    {"name": "LZtLcK", "marks": 34},
    {"name": "rnV9", "marks": 5},
    {"name": "9sWJUerFOC", "marks": 69},
    {"name": "6d2HDOL", "marks": 47},
    {"name": "FW", "marks": 94},
    {"name": "oMzL2N", "marks": 55},
    {"name": "CJmDh0o2", "marks": 41},
    {"name": "zZo", "marks": 40},
    {"name": "I", "marks": 16},
    {"name": "4", "marks": 53},
    {"name": "Jfgq9", "marks": 38},
    {"name": "03CBF93v", "marks": 46},
    {"name": "Br", "marks": 64},
    {"name": "hRD", "marks": 98},
    {"name": "Yg1Nj0YE", "marks": 11},
    {"name": "HXTA", "marks": 63},
    {"name": "xTaB", "marks": 97},
    {"name": "ekjytul", "marks": 75},
    {"name": "C4JeeB", "marks": 49},
    {"name": "7", "marks": 92},
    {"name": "VGXc2m", "marks": 47},
    {"name": "Ig6Xxy", "marks": 56},
    {"name": "vtHIxlrlXI", "marks": 37},
    {"name": "xnKs12", "marks": 8},
    {"name": "NDE", "marks": 63},
    {"name": "X2AC", "marks": 33},
    {"name": "G5", "marks": 33},
    {"name": "LpZc", "marks": 97},
    {"name": "jEQ7RneJ", "marks": 65},
    {"name": "1DJGQIsfoY", "marks": 61},
    {"name": "F", "marks": 43},
    {"name": "pAIwM", "marks": 14},
    {"name": "R5UwLwF", "marks": 73},
    {"name": "NlHU06DQlL", "marks": 54},
    {"name": "Tbe", "marks": 69},
    {"name": "Ws91MKASA", "marks": 50},
    {"name": "5kRxKo4k", "marks": 38},
    {"name": "A3", "marks": 72},
    {"name": "daWX42UrFv", "marks": 38},
    {"name": "5MSqb2J", "marks": 76},
    {"name": "fT4K", "marks": 56},
    {"name": "jE8a1sxl", "marks": 77},
    {"name": "eiPitAo8fI", "marks": 5},
    {"name": "Zomdcb4nFA", "marks": 70},
    {"name": "xrkXrlH", "marks": 17},
    {"name": "BERP3gYnl", "marks": 96},
    {"name": "s", "marks": 56},
    {"name": "57MpSV9", "marks": 59},
    {"name": "x5U3p", "marks": 46},
    {"name": "SGwt3qFAxm", "marks": 68},
    {"name": "RtsOF", "marks": 32},
    {"name": "nqAwTbaV", "marks": 4},
    {"name": "Q8fP7w4ZBm", "marks": 32},
    {"name": "M0nfIMA", "marks": 95},
    {"name": "hCSyJf", "marks": 68},
    {"name": "PEa", "marks": 13},
    {"name": "U5", "marks": 51},
    {"name": "DenHcJ5uP3", "marks": 66},
    {"name": "R9", "marks": 11},
    {"name": "BCy", "marks": 16},
    {"name": "sS1l5", "marks": 85},
    {"name": "apul1QwxJ", "marks": 60},
    {"name": "C", "marks": 24},
    {"name": "Rm5K7h", "marks": 7},
    {"name": "0h8zCW", "marks": 88},
    {"name": "VDgVmr", "marks": 60},
    {"name": "vB5w1hRv8I", "marks": 45},
    {"name": "7kFvkzzE2", "marks": 61},
    {"name": "vHHi7", "marks": 10},
    {"name": "E2Up", "marks": 60},
    {"name": "HngVBDgs", "marks": 90},
    {"name": "GtioxmqE3", "marks": 75},
    {"name": "Chw", "marks": 0},
    {"name": "lJgqk8voP", "marks": 16},
    {"name": "1tcc", "marks": 97},
    {"name": "4SevJ8V3Pn", "marks": 87},
    {"name": "LsZh6oh", "marks": 48},
    {"name": "hJC8VX5jf", "marks": 10},
    {"name": "sRxSJ2upA", "marks": 57},
    {"name": "NVhnGnX9k", "marks": 88},
    {"name": "kt", "marks": 80},
    {"name": "5U", "marks": 11},
    {"name": "d", "marks": 12},
    {"name": "E", "marks": 95},
    {"name": "t3CVmOF", "marks": 3},
    {"name": "l", "marks": 69},
    {"name": "KltpZpRLxy", "marks": 81},
    {"name": "aR8", "marks": 89},
    {"name": "i", "marks": 19},
    {"name": "eO0", "marks": 15},
    {"name": "R3M", "marks": 51},
    {"name": "Scelxb7Fq", "marks": 70},
    {"name": "48pBg1BV6x", "marks": 62},
    {"name": "VFyeRk4", "marks": 34}
]

@app.route('/api', methods=['GET'])
def get_marks():
    names = request.args.getlist('name')  # Get all 'name' query parameters
    marks = [next((student['marks'] for student in students_marks if student['name'] == name), "Student not found") for name in names]
    return json.dumps({"marks": marks})

if __name__ == '__main__':
    app.run(debug=True)
